#!/bin/bash
# Script to prepare the SQL RAG Dashboard project for GitHub upload

echo "Preparing SQL RAG Dashboard for GitHub..."

# Create directories if they don't exist
mkdir -p metadata

# Remove test files that shouldn't be included
echo "Removing test files..."
rm -f test_*.py
rm -f *_test.py
rm -f final_test.py
rm -f test_functionality.py
rm -f test_mcp.py
rm -f test_query.py
rm -f test_wrapper_deletion.py
rm -f test_direct_deletion.py
rm -f test_app_deletion.py
rm -f test_tables.py
rm -f fix_tables.py

# Remove database files (they'll be regenerated by users)
echo "Removing database files..."
rm -f *.db
rm -f schema.json

# Remove environment and cache files
echo "Removing environment and cache files..."
rm -f .env
rm -rf __pycache__
rm -rf .gradio
rm -rf venv

# Remove CSV files
echo "Removing CSV files..."
rm -f *.csv

# Check for critical files
echo "Checking for critical files..."
CRITICAL_FILES=("app.py" "db_utils.py" "llm_utils.py" "mcp_utils.py" "db_manager.py" "create_sample_tables.py" "README.md" "LICENSE" "requirements.txt" ".env.example" "README_DB_TOOLS.md")

for file in "${CRITICAL_FILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "WARNING: Critical file '$file' is missing!"
  else
    echo "✓ Found $file"
  fi
done

# List files that will be included in the repository
echo -e "\nFiles to be included in the GitHub repository:"
ls -la | grep -v "^d" | awk '{print $9}' | grep -v "^\." | sort

echo -e "\nDirectories to be included:"
find . -type d -not -path "*/\.*" -not -path "./venv*" | sort

echo -e "\nPrepared for GitHub upload!"
echo "You can now run:"
echo "  git add ."
echo "  git commit -m \"Initial commit\""
echo "  git push" 